# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import cases_pb2 as cases__pb2


class InsertStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InsertCase = channel.unary_unary(
                '/casesp.Insert/InsertCase',
                request_serializer=cases__pb2.CaseReq.SerializeToString,
                response_deserializer=cases__pb2.CaseRes.FromString,
                )


class InsertServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InsertCase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InsertServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InsertCase': grpc.unary_unary_rpc_method_handler(
                    servicer.InsertCase,
                    request_deserializer=cases__pb2.CaseReq.FromString,
                    response_serializer=cases__pb2.CaseRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'casesp.Insert', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Insert(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InsertCase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/casesp.Insert/InsertCase',
            cases__pb2.CaseReq.SerializeToString,
            cases__pb2.CaseRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
