# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cases.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cases.proto',
  package='casesp',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0b\x63\x61ses.proto\x12\x06\x63\x61sesp\"d\n\x04\x43\x61se\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08location\x18\x03 \x01(\t\x12\x0b\n\x03\x61ge\x18\x04 \x01(\x05\x12\x14\n\x0cinfectedtype\x18\x05 \x01(\t\x12\r\n\x05state\x18\x06 \x01(\t\"%\n\x07\x43\x61seReq\x12\x1a\n\x04\x63\x61se\x18\x01 \x01(\x0b\x32\x0c.casesp.Case\"%\n\x07\x43\x61seRes\x12\x1a\n\x04\x63\x61se\x18\x01 \x01(\x0b\x32\x0c.casesp.Case2:\n\x06Insert\x12\x30\n\nInsertCase\x12\x0f.casesp.CaseReq\x1a\x0f.casesp.CaseRes\"\x00\x62\x06proto3'
)




_CASE = _descriptor.Descriptor(
  name='Case',
  full_name='casesp.Case',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='casesp.Case.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='casesp.Case.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='location', full_name='casesp.Case.location', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='age', full_name='casesp.Case.age', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='infectedtype', full_name='casesp.Case.infectedtype', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='state', full_name='casesp.Case.state', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=123,
)


_CASEREQ = _descriptor.Descriptor(
  name='CaseReq',
  full_name='casesp.CaseReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='case', full_name='casesp.CaseReq.case', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=162,
)


_CASERES = _descriptor.Descriptor(
  name='CaseRes',
  full_name='casesp.CaseRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='case', full_name='casesp.CaseRes.case', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=201,
)

_CASEREQ.fields_by_name['case'].message_type = _CASE
_CASERES.fields_by_name['case'].message_type = _CASE
DESCRIPTOR.message_types_by_name['Case'] = _CASE
DESCRIPTOR.message_types_by_name['CaseReq'] = _CASEREQ
DESCRIPTOR.message_types_by_name['CaseRes'] = _CASERES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Case = _reflection.GeneratedProtocolMessageType('Case', (_message.Message,), {
  'DESCRIPTOR' : _CASE,
  '__module__' : 'cases_pb2'
  # @@protoc_insertion_point(class_scope:casesp.Case)
  })
_sym_db.RegisterMessage(Case)

CaseReq = _reflection.GeneratedProtocolMessageType('CaseReq', (_message.Message,), {
  'DESCRIPTOR' : _CASEREQ,
  '__module__' : 'cases_pb2'
  # @@protoc_insertion_point(class_scope:casesp.CaseReq)
  })
_sym_db.RegisterMessage(CaseReq)

CaseRes = _reflection.GeneratedProtocolMessageType('CaseRes', (_message.Message,), {
  'DESCRIPTOR' : _CASERES,
  '__module__' : 'cases_pb2'
  # @@protoc_insertion_point(class_scope:casesp.CaseRes)
  })
_sym_db.RegisterMessage(CaseRes)



_INSERT = _descriptor.ServiceDescriptor(
  name='Insert',
  full_name='casesp.Insert',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=203,
  serialized_end=261,
  methods=[
  _descriptor.MethodDescriptor(
    name='InsertCase',
    full_name='casesp.Insert.InsertCase',
    index=0,
    containing_service=None,
    input_type=_CASEREQ,
    output_type=_CASERES,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_INSERT)

DESCRIPTOR.services_by_name['Insert'] = _INSERT

# @@protoc_insertion_point(module_scope)
