apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: uhcorona/imgapi:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8000